name: Build APK
on:
  push:
    branches: [ gh-pages ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      
      - uses: actions/setup-java@v4
        with:
          java-version: 17
      
      - name: Download TWA
        run: |
          curl -L -o twa.jar https://github.com/GoogleChromeLabs/TWA/releases/download/1.0/TWA-1.0.jar
      - name: Build
        run: |
          java -jar twa.jar "https://hj7799.github.io/photo-web/" -n PhotoNaming -o output
      
      - uses: actions/upload-artifact@v4
        with:
          name: PhotoNaming
          path: output/*.apk